### ISSUE TITLE
Add support for metric alert thresholds

### ISSUE THREAD

**Issue by athompson-r7** [rapid7/dogwatch#4]
Add support for thresholds on [metric_alert(s)](http://docs.datadoghq.com/api/#monitors).  From the docs:

> ###### METRIC ALERT OPTIONS
> 
> _These options only apply to metric alerts._
> - `thresholds` a dictionary of thresholds by threshold type. Currently we have two threshold types for >metric alerts: critical and warning. Critical is defined in the query, but can also be specified in this option. Warning threshold can only be specified using the thresholds option.
>   Example: `{'critical': 90, 'warning': 80}`

**Comment by erran-r7** [comment]
@athompson-r7 in https://github.com/rapid7/dogwatch/pull/10 I have a proposed solution for this. Let's discuss there?
