### ISSUE TITLE
Need clearer error messaging

### ISSUE THREAD

**Issue by ghost** [rapid7/dogwatch#5]
Currently, trying to add some monitors and my queries are clearly broken, but all I'm seeing is:

"error  ["The value provided for parameter 'query' is invalid"]"

I think it'd be helpful to see at the very least what the query was that it was trying to use.

**Comment by dgreene-r7** [comment]
We don't have a method for validating the query except for submitting it to DataDog and hoping for the best. Until their API returns details about why the query was invalid, we can't fix this.
